baseurl = "https://mhBrice.github.io/"
relativeurls = true
title = "Marie-Hélène Brice"
copyright = "2018-2021 Marie-Hélène Brice. "
theme = "ananke"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""
enableRobotsTXT = true

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true

# Navigation Links
[permalinks]
    post = "/:year/:month/:day/:slug/"

[markup.goldmark.renderer]
    unsafe= true

[languages]
  [languages.en]
    languageCode = "en-us"
    title = ":deciduous_tree:"
    weight = 1
    contentDir = "content/en"
    [[languages.en.menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[languages.en.menu.main]]
        name = "Research"
        url = "/research/"
        weight = 2
    [[languages.en.menu.main]]
        name = "Publications"
        url = "/publications/"
        weight = 3
    [[languages.en.menu.main]]
        name = "Communications"
        url = "/talks/"
        weight = 4
    [[languages.en.menu.main]]
        name = "Teaching"
        url = "/teaching/"
        weight = 5
    [[languages.en.menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 6
  [languages.fr]
    title = ":evergreen_tree:"
    weight = 2
    contentDir = "content/fr"
    [[languages.fr.menu.main]]
        name = "Accueil"
        url = "/"
        weight = 1
    [[languages.fr.menu.main]]
        name = "Recherche"
        url = "/research/"
        weight = 2
    [[languages.fr.menu.main]]
        name = "Publications"
        url = "/publications/"
        weight = 3
    [[languages.fr.menu.main]]
        name = "Communications"
        url = "/talks/"
        weight = 4
    [[languages.fr.menu.main]]
        name = "Enseignement"
        url = "/teaching/"
        weight = 5
    [[languages.fr.menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 6


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  name = "Marie-Hélène Brice"
  role = "PhD candidate in ecology"
  organization = "Département de sciences biologiques, Université de Montréal"
  organization_url = "https://bio.umontreal.ca/nc/accueil/"
  # twitter = "mariehbrice"
  github = "https://github.com/mhbrice"
  address = "Département de sciences biologiques, Pavillon Marie-Victorin, Université de Montréal, Montréal, H2V 2S9"
  #office_hours = "Send me an email for setting an appointment."
  email = "marie-helene.brice@umontreal.ca"
  # phone = "514-318-8945"
  skype = "mariehbrice"
  skype_name = "Marie-Hélène Brice"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  #  For more info on the highlighting options, see:   # https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = ["bash", "html", "julia", "python", "r", "rust", "xml", "yaml"]
  highlight_style = "monokai"
  # highlight_version = "9.12.0"

  # I follow the example given with highlightjs in academic theme to add mathjax and lealfet
  mathjax = true
  leaflet = true

  font = ["Raleway"]

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = [
    "/css/perso.css",
    "/css/creativecommons.css",
    "/css/flag-icon.css",
    "https://fonts.googleapis.com/css?family=Open+Sans"
  ]
  custom_js  = [
    "/js/mapoffice.js",
  ]

# google fonts
# font = ["Changa One"]



# Taxonomies.
[taxonomies]
  tag = "tags"
  # category = "categories"
