name = "KevCaz"
license = "MIT"
licenselink = "https://github.com/KevCaz/hugo-KevCaz/blob/master/LICENSE.md"
description = "My custom theme"
homepage = "https://github.com/KevCaz/KevCaz.github.io"
tags = ["blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["perso"]
min_version = "0.18"
banner = "img/banner.png"


[author]
  name = "Kevin Cazelles"
  homepage = "https://kevcaz.github.io/"
